<h2 id='warning'><?php echo $this->message?></h2>
<div id='list'>
	<?php 
	foreach ($this->maeCollection as $mae)
	{
		
		?>
			<table border='0'>
				<tr>
					<td style='text-align: left'>
							<a href='<?php echo PATH_APPLICATION; ?>/Mae/edit?id=<?php echo ($mae->pk_mae); ?>'>
								<?php echo ($mae->pk_mae);?>
							</a><br>
											</td>
					<td style='vertical-align: top'>
						<a href='<?php echo PATH_APPLICATION; ?>/Mae/remove?id=<?php echo ($mae->pk_mae); ?>'><button>Delete</button></a>	
					</td>
				</tr>
			</table>
		<?php		
	}
	?>
</div>
