<h2 id='warning'><?php echo $this->message?></h2>
<center>
<form action='<?php echo PATH_APPLICATION; ?>/Mae/save' method='post'>
<table>
	<tr style='display:none'>
		<td colspan='2'>
			<input name='pk_mae' value='<?php echo $this->mae['pk_mae'];?>' id='pk_mae' type='hidden'>
		</td>
	</tr>
	<tr>
		<td>
			Professor:
		</td>
		<td>
			<select name='pk_professor'>
				<?php
					foreach ($this->professorCollection as $professor)
					{
						?>
							<option <?php echo $this->mae['fk_professor'] == $professor->pk_professor ? 'selected' : ''; ?> value="<?php echo $professor->pk_professor; ?>">
								<?php echo $professor->nome; ?>
							</option>
						<?php
					}
			?>
			</select>
		</td>
	</tr>
	<tr>
		<td>
			<input type='submit'>
		</td>
	</tr>
</table>
</form>
</center>
	<script type='text/javascript'>
		$(function() {
		});
	</script>