<h2 id='warning'><?php echo $this->message?></h2>
<center>
<form action='<?php echo PATH_APPLICATION; ?>/Professor/save' method='post'>
<table>
	<tr style='display:none'>
		<td colspan='2'>
			<input name='pk_professor' value='<?php echo $this->professor['pk_professor'];?>' id='pk_professor' type='hidden'>
		</td>
	</tr>
	<tr>
		<td>
			Nome:
		</td>
		<td>
			<input name='nome' value='<?php echo $this->professor['nome']; ?>' maxlength='60' id='nome' type='text'>
		</td>
	</tr>
	<tr>
		<td>
			Salario:
		</td>
		<td>
			<input name='salario' value='<?php echo $this->professor['salario']; ?>' id='salario' type='text'>
		</td>
	</tr>
	<tr>
		<td>
			<input type='submit'>
		</td>
	</tr>
</table>
</form>
</center>
	<script type='text/javascript'>
		$(function() {
		});
	</script>