<h2 id='warning'><?php echo $this->message?></h2>
<center>
<form action='<?php echo PATH_APPLICATION; ?>/Professor/save' method='post'>
<table>
	<tr>
		<td>
			Nome:
		</td>
		<td>
			<input name='nome' value='' maxlength='60' id='nome' type='text'>
		</td>
	</tr>
	<tr>
		<td>
			Salario:
		</td>
		<td>
			<input name='salario' value='' id='salario' type='text'>
		</td>
	</tr>
	<tr>
		<td>
			<input type='submit'>
		</td>
	</tr>
</table>
</form>
</center>
	<script type='text/javascript'>
		$(function() {
		});
	</script>