<html xmlns='http://www.w3.org/1999/xhtml'>
<head>
<title>tchelinux</title>
<link rel='stylesheet' type='text/css' href='/tchelinux/public/styles/zend.generic.css' />
<link rel='stylesheet' href='/tchelinux/public/styles/jquery.treeview.css' />
<script src='/tchelinux/public/scripts/jquery.js' type='text/javascript'></script>
<script src='/tchelinux/public/scripts/default.js' type='text/javascript'></script>
<script src='/tchelinux/public/scripts/jquery.treeview.js' type='text/javascript'></script>
</head>
<body>
	<?php echo $this->render($this->header)?>
	<div id='container'>
	<!-- Content -->
	<?php echo $this->render($this->body)?>
	</div>
</body>
</html>