<?php
$session = Zend_Registry::get('session');
?>
<div id='header'>
	Generate by TheWebMind beta 2.0 at 12/04/2010
</div>

<div id='menu' class='menu'>
	<ul id='browser' class='filetree'>
		<li>
			<span class='folder'>Professor</span>
			<ul>
				<li><span class='file'><a href='<?php echo PATH_APPLICATION; ?>/Professor/add'>Add</a></span></li>
				<li><span class='file'><a href='<?php echo PATH_APPLICATION; ?>/Professor/list'>List</a></span></li>
			</ul>
		</li>
		<li>
			<span class='folder'>Aluno</span>
			<ul>
				<li><span class='file'><a href='<?php echo PATH_APPLICATION; ?>/Aluno/add'>Add</a></span></li>
				<li><span class='file'><a href='<?php echo PATH_APPLICATION; ?>/Aluno/list'>List</a></span></li>
			</ul>
		</li>
		<li>
			<span class='folder'>Professor Aluno</span>
			<ul>
				<li><span class='file'><a href='<?php echo PATH_APPLICATION; ?>/ProfessorAluno/add'>Add</a></span></li>
				<li><span class='file'><a href='<?php echo PATH_APPLICATION; ?>/ProfessorAluno/list'>List</a></span></li>
			</ul>
		</li>
		<li>
			<span class='folder'>Mae</span>
			<ul>
				<li><span class='file'><a href='<?php echo PATH_APPLICATION; ?>/Mae/add'>Add</a></span></li>
				<li><span class='file'><a href='<?php echo PATH_APPLICATION; ?>/Mae/list'>List</a></span></li>
			</ul>
		</li>	</ul>
</div>