<h2 id='warning'><?php echo $this->message?></h2>
<center>
<form action='<?php echo PATH_APPLICATION; ?>/Aluno/save' method='post'>
<table>
	<tr style='display:none'>
		<td colspan='2'>
			<input name='pk_aluno' value='<?php echo $this->aluno['pk_aluno'];?>' id='pk_aluno' type='hidden'>
		</td>
	</tr>
	<tr>
		<td>
			<input type='submit'>
		</td>
	</tr>
</table>
</form>
</center>
	<script type='text/javascript'>
		$(function() {
		});
	</script>